version: '3'
services:
  mysql:
    container_name: mysql
    image: 'mysql:8.0'
    volumes:
      - mysql-keymager-volume:/var/lib/mysql
    restart: always
    network_mode: bridge
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  mysql-keymager-volume: