version: '3'
services:
  mysql:
    image: 'mysql:8.0'
    volumes:
      - mysql-keymager-volume:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  mysql-keymager-volume: