micronaut:
  application:
    name: keymanagerGrpc
datasources:
  default:
    url: ${DB_URI:`jdbc:mysql://localhost:3306`}/${DB_DATABASE}
    driverClassName: ${DB_DRIVER:`com.mysql.cj.jdbc.Driver`}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    schema-generate: CREATE
    dialect: ${DB_DIALECT:`MYSQL`}
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

erp.itau:
  host: http://${ITAU_URL:`localhost:9091`}
  consulta.clientes: ${CONSULTA_CLIENTES:`/api/v1/clientes`}

bcb:
  host: http://${BCB_URL:`localhost:8082`}
  pix.keys: ${CONSULTA_CLIENTES:`/api/v1/pix/keys`}
